### ISSUE TITLE
Feedback of Beta phase

### ISSUE THREAD

**Issue by aceisace** [aceisace/9.7-E-Paper-Calendar-software#2]
**Info**
As I do _not_ have the 9.7" E-Paper, it's quite difficult for me to develop the software since I can't perform any testing myself. This issue is mainly for those, who have the 9.7" E-Paper display and want to test the code and provide feedback.

**Kind note**
If you want to support the development of this software, the best way would be to do so via a donation (please ask me for details). That way, I can get myself the 9.7" E-Paper and speed up the development a lot.

**Comment by aceisace** [comment]
## Hooray, the 9.7" E-Paper software has just been launched!

**Comment by Crickus** [comment]
**@aceisace** 
Hi Ace. Congratulate you with new public repo lunching :)
But I have found one issue so long. Second day after few iterations script stops with this message.
Fetching events from your calendar

```
Traceback (most recent call last):
  File "E-Paper.py", line 340, in <module>
    main()
  File "E-Paper.py", line 198, in main
    decode = str(urlopen(icalendars).read().decode())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```
As I understood it is some access problem. Maybe Google changed something in it's API?

**Comment by Crickus** [comment]
**@aceisace** 
`https://raw.githubusercontent.com/aceisace/9.7-E-Paper-Calendar-software/master/Installer-with-debug.sh` from Single Line Installer generates 404 error. Is it normal?

**Comment by Crickus** [comment]
**@aceisace** 
I made the image you asked for.
![20190324_191149_1](https://user-images.githubusercontent.com/22008248/54883106-78b2e280-4e6a-11e9-9371-7fd3077bce75.jpg)

**Comment by aceisace** [comment]
@Crickus 
Hi Dimka, thanks for your comments.

First thing first. the error `urllib.error.HTTPError: HTTP Error 500: Internal Server Error` is caused by google's own servers and is therefore only a temporary error. It should have been resolved automatically before long.

About the installer, thanks for already testing the installer. As I mentioned, it is not ready yet, let alone useable, at least for the next few days. Once I can get it working without errors, I'll ask you to test it after that.

Also, thanks for the image you posted. I'll add it on the README.

**Comment by aceisace** [comment]
I'll be closing this issue now since the beta phase is also complete.
