### ISSUE TITLE
Single Line Installer

### ISSUE THREAD

**Issue by aceisace** [aceisace/9.7-E-Paper-Calendar-software#3]
This is an issue created solely for the single line installer of the 9.7" E-Paper Calendar software. The purpose if this issue is to help set up the installer in such a way that it has no issues, is easy to use and contains options to update, install or uninstall the software.

The line below shows the current status of the E-Paper software.

### Current status: Working

**Comment by aceisace** [comment]
@Crickus 
OK, I've fixed the bug with the incorrect installer URL. It was a typo in the filename.
Running the installer should work, but it is not guaranteed to work. Please make a backup of your current E-Paper files before running to prevent the possibility of undedired deletions. Thanks in advance.

**Comment by aceisace** [comment]
@Crickus 
I've fixed the problem(s) with the Installer now. Could you please try running the installer to see if it works?
Thanks in advance :)

**Comment by Crickus** [comment]
**@aceisace** 
I installed SLI (Single Line Installer) as you asked. You was very optimistic about "it may take 30 min". It lasted 65 min to finish the installing on my Zero W with 100 % CPU load. 
Only mistakes I had seen during installation was few strings about missing directory.
```
Finished installing libraries
Installing the E-Paper-Calendar Software for your display
Cloning into '9.7-E-Paper-Calendar-software'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 1011 (delta 57), reused 0 (delta 0), pack-reused 910
Receiving objects: 100% (1011/1011), 2.16 MiB | 653.00 KiB/s, done.
Resolving deltas: 100% (504/504), done.
bash: line 95: cd: E-Paper-Calendar-with-iCal-sync-and-live-weather: No such file or directory
cp: cannot stat 'Calendar': No such file or directory
cp: cannot stat 'README.md': No such file or directory
cp: cannot stat 'LICENSE': No such file or directory
cp: cannot stat '.git': No such file or directory
bash: line 102: cd: /home/pi/E-Paper-Master/Calendar: No such file or directory
cp: cannot stat 'settings.py.sample': No such file or directory
rm: cannot remove 'E-Paper-Calendar-with-iCal-sync-and-live-weather': No such file or directory
Setting up the required E-Paper driver files
bash: line 111: cd: /home/pi/E-Paper-Master/Calendar/Driver-files: No such file or directory
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for clock_gettime in -lrt... yes
checking for doxygen... no
configure: WARNING: Doxygen not found - continuing without Doxygen support
checking for ranlib... ranlib
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make  all-recursive
```
 Another problem is what Calendar folder was not moved into E-Paper-Master folder during script execution.
![2019-03-26_162747](https://user-images.githubusercontent.com/22008248/55005203-40371400-4fe4-11e9-85cc-ebf910cfd749.jpg)

You propose to insert private settings into settings.py file, but you didn't create it. Only sample one.
![2019-03-26_163030](https://user-images.githubusercontent.com/22008248/55005447-b2a7f400-4fe4-11e9-9c6b-e17ab79061dd.jpg)
 
I copied the old script file with Russian weather changings. But original one from the installation package is workable too.

**Comment by aceisace** [comment]
@Crickus 
Hi Dimka, sorry, I didn't mean to be optimistic, it's just that from amongst all the installs I did myself, none of them lasted more than 30 minutes. It might be related to 2 things, either the nextwork speed is slow, so downloading takes longer than expected or it might be because of the system has not been updated for a long time. I'm sorry it took much longer for you. But now that all packages are up-to-date, it won't take as long anymore. 

Thanks for the bug-report about the Installer. I've just now fixed the problem with the incorrect folder name so there should no longer be any errors. The other errors are also related to the previous one and therefore should have been fixed along. If you encounter any more errors, please report them here. Thanks in advance.

**Comment by Crickus** [comment]
**@aceisace** 
Don't apologize. Program folder was installing 15 or 20 minutes. The rest of the time Debian was upgrading. I wrote total time only for information. As we may see it very depends on overall system state.
I didn't witness any other problems during installation, so I think what installer must do its job well now :)

**Comment by aceisace** [comment]
@Crickus 
Thanks for your help. It's good to hear that the installer is working fine now  :).
I can now remove the warning on the README.

**Comment by Crickus** [comment]
**@aceisace** 
Hi Ace. Did you change weather API part of the script when you were speeding it up?
Two times I have seen big N/A instead of all weather icons and information. Never seen it before. As I understand this thing are shown when weather server timeout error has occurred?

**Comment by aceisace** [comment]
@Crickus 
The speed-improvement I made in the weather-section only sets up the weather __before__ the loop, so that the weather can be __fetched__ faster in the loop. Previously, both, the setup and the fetching were inside the loop. This used to take much longer.

As a result, there should have been no changes to the functionality of the weather section itself. The reason you see a big N/A (not available) icon on the Display is because when the script was trying to check the connection to Openweathermap's API servers, something went wrong (timeout etc.).

But even when a good internet connection is provided, there are 2 causes this could happen:
* Openweathermap's API servers are not available all the time, especially for 'free' users. They wrote on their website that the servers are available for about 95% of the time. Hence, sometimes seeing the N/A icon is not all that rare.

* It might also be possible that the E-Paper.py file envountered a 'more serious' error, i.e. one not strictly related to openweathermap (for example, the iCalendar). If that was the case, the main script is not running anymore and you should have seen the same image twice (once in the previous hour and once in the current hour). The easy fix for this is to delete the 'current-image.bmp' in the Calendar folder and reboot the Raspberry.

Do let me know if the problem is fixed. Thanks in advance.

**Comment by Crickus** [comment]
**@aceisace** 
Hi Ace. It was not problem or issue, just sharing of observation.
It has repeated just once after I post the message, so we may think about it as about closed issue :)
It was connected with Openweather site availability. I almost sure about it.

**Comment by aceisace** [comment]
@Crickus 
Hi Dimka. Glad to hear the problem was resolved by itself. I'll be closing this issue now. If you feel a need to re-open this issue, feel free to do so. Thanks in advance
