### ISSUE TITLE
Script stopped working

### ISSUE THREAD

**Issue by Crickus** [aceisace/9.7-E-Paper-Calendar-software#4]
Hello, @aceisace 
Sorry to bother you. But E-Paper script stopped working for me two days ago.
It doesn't make image since Saturday.
Reinstalling didn't help. I tried to comment strings with error in the script, but it caused new errors.
At the moment it looks like that
```
pi@raspberrypi:~/E-Paper-Master/Calendar $ python3.5 E-Paper.py 
_________Starting new loop___________

Date: Mon 2 Sep 19, Time: 13:06

Traceback (most recent call last):
  File "E-Paper.py", line 340, in <module>
    main()
  File "E-Paper.py", line 100, in main
    image.paste(im_open(dpath+str(numbers)+'.jpeg'), positions['f'+str(cal[5].index(numbers)+1)])
UnboundLocalError: local variable 'numbers' referenced before assignment
pi@raspberrypi:~/E-Paper-Master/Calendar $ 
```
Could you help with some advise?

**Comment by aceisace** [comment]
@Crickus  Hi Dimka,
sorry the script stopped working. The error was caused by a simple copy-paste error. I've fixed it now so could you try using the updated script now?

**Comment by Crickus** [comment]
Hi @aceisace 
Thank you for quick response.
Line 340 didn't give up :(
pi@raspberrypi:~/E-Paper-Master/Calendar $ python3.5 E-Paper.py _________Starting new loop___________

Date: Fri 6 Sep 19, Time: 00:05

Connecting to Openweathermap API servers...
weather data:
Temperature: 11 °C
Humidity: 100%
weather-icon name: wi-night-alt-cloudy-windy
Wind speed: 1km/h
Sunrise-time: 6:45
Sunset time: 19:59
Cloudiness: 0%
Weather description: Mist

Fetching events from your calendar

Traceback (most recent call last):
  File "E-Paper.py", line 340, in <module>
    main()
  File "E-Paper.py", line 273, in main
    news.append(multiline_text(rss_feed[title], 1100))
IndexError: list index out of range
pi@raspberrypi:~/E-Paper-Master/Calendar $

**Comment by Crickus** [comment]
Thank you for helping, @aceisace 
I provided some testing with your modified script and the old one. It looks like the problem is caused by my settings section. To be precise - rss url section.
Most of my sources stopped working for some reason.
They have specific formatting and looks like xml scripts.
   https://www.anekdot.ru/rss/export_top.xml
   https://bash.im/rss/
But according to feedparser documentation it's not a problem. Their tags  looks OK too.
But your script cannot parse them. It cannot fetch no title, no summary, no any other elements.
Something in those page formatting cause a problem with parsing.
Could you look at them when you'll have some free time, please?
Thank you in advance.

**Comment by Crickus** [comment]
I did few tests with different settings.
Still have 

```
pi@raspberrypi:~/E-Paper-Master/Calendar $ python3.5 E-Paper.py 
_________Starting new loop___________

Date: Tue 10 Sep 19, Time: 20:02

Connecting to Openweathermap API servers...
weather data:
Temperature: 19 °C
Humidity: 68%
weather-icon name: wi-night-clear
Wind speed: 1km/h
Sunrise-time: 6:51
Sunset time: 19:50
Cloudiness: 0%
Weather description: ясно

Fetching events from your calendar

Traceback (most recent call last):
  File "E-Paper.py", line 343, in <module>
    main()
  File "E-Paper.py", line 276, in main
    news.append(multiline_text(rss_feed[title], 1100))
IndexError: list index out of range
```
Can it be connected with abnormal weeks quantity in this September and free lines calculating in your script?
![20190910_201326](https://user-images.githubusercontent.com/22008248/64635127-a33c2c00-d407-11e9-9d72-10fdadd7a36b.jpg)

**Comment by aceisace** [comment]
@Crickus
Hi Dimka, sorry for the late reply. I‘m currently outside the country so it‘s a bit difficult to work on the software right now. I‘ll be back around mid October and will work on the fixes then.

You got the error right though. It is related to the fact that this month‘s layout takes up one more row. Due to that, there is less space for rss feeds. In the RSS section of the E-Paper.py. file, try reducing the number of RSS feeds to be displayed. This is as much help as I can offer currently.
