### ISSUE TITLE
Too long russian weather description

### ISSUE THREAD

**Issue by Crickus** [aceisace/9.7-E-Paper-Calendar-software#5]
Hi, Ace.
Found new issue today. Russian variant of "partly cloudy" is too long for your text box.
Could you point me where to fix it, please?
Date: Tue 29 Oct 19, Time: 14:33
```

Connecting to Openweathermap API servers...
weather data:
Temperature: 9 °C
Humidity: 66%
weather-icon name: wi-cloudy-windy
Wind speed: 4km/h
Sunrise-time: 7:07
Sunset time: 17:07
Cloudiness: 75%
Weather description: облачно с прояснениями

Traceback (most recent call last):
  File "E-Paper.py", line 340, in <module>
    main()
  File "E-Paper.py", line 180, in main
    write_text(250,50, weather_description, (700, 90))
  File "E-Paper.py", line 108, in write_text
    raise ValueError('Sorry, your text is too big for the box')
ValueError: Sorry, your text is too big for the box
```

**Comment by aceisace** [comment]
@Crickus 
Hi Dimka, You can try replacing line 108 from:
`raise ValueError('Sorry, your text is too big for the box')`
to:
`pass`
as a temporary fix. This will bypass the error if the text is too long. Hope this helps.

**Comment by Crickus** [comment]
@aceisace 
Hi Ace. I already fix it with increasing space for this block and moving it slightly left.
It forces my inner perfectionist to cry. But it's work good as a temporary fix.
Thank you for help.
